import unittest
from traceclip.detector import detect_issues
from traceclip.fixer import fix_file

class TestTraceclip(unittest.TestCase):
    def test_unused_imports(self):
        code = """import os
import sys
from collections import defaultdict, Counter
import math as m

d = defaultdict(int)
"""
        issues = detect_issues(code, "test.py")
        types = [i.issue_type for i in issues]
        messages = [i.message for i in issues]
        
        self.assertIn("unused_import", types)
        # os, sys, Counter, m are unused
        unused_names = [m for m in messages if "Unused import" in m]
        self.assertEqual(len(unused_names), 4)
        self.assertTrue(any("os" in m for m in unused_names))
        self.assertTrue(any("sys" in m for m in unused_names))
        self.assertTrue(any("Counter" in m for m in unused_names))
        self.assertTrue(any("math as m" in m for m in unused_names))

    def test_wildcard_import(self):
        code = "from math import *"
        issues = detect_issues(code, "test.py")
        types = [i.issue_type for i in issues]
        self.assertIn("wildcard_import", types)

    def test_dead_functions(self):
        code = """def dead_func(x):
    return x * 2

def recursive_dead_func(n):
    if n <= 1:
        return 1
    return n * recursive_dead_func(n-1)

def active_func():
    return 42

print(active_func())
"""
        issues = detect_issues(code, "test.py")
        dead_funcs = [i.message for i in issues if i.issue_type == "dead_function"]
        self.assertEqual(len(dead_funcs), 2)
        self.assertTrue(any("dead_func" in m for m in dead_funcs))
        self.assertTrue(any("recursive_dead_func" in m for m in dead_funcs))
        self.assertFalse(any("active_func" in m for m in dead_funcs))

    def test_placeholder_variables(self):
        code = """API_KEY = "your_api_key_here"
PASSWORD = "insert_password_here"
token = "enter_token_here"
my_val = "normal value"
"""
        issues = detect_issues(code, "test.py")
        placeholders = [i.message for i in issues if i.issue_type == "placeholder_var"]
        self.assertEqual(len(placeholders), 3)
        self.assertTrue(any("API_KEY" in m for m in placeholders))
        self.assertTrue(any("PASSWORD" in m for m in placeholders))
        self.assertTrue(any("token" in m for m in placeholders))
        self.assertFalse(any("my_val" in m for m in placeholders))

    def test_stub_functions(self):
        code = """def stub1():
    pass

def stub2():
    ...

def stub3():
    raise NotImplementedError

def active():
    print("hello")
"""
        issues = detect_issues(code, "test.py")
        stubs = [i.message for i in issues if i.issue_type == "stub_function"]
        self.assertEqual(len(stubs), 3)
        self.assertTrue(any("stub1" in m for m in stubs))
        self.assertTrue(any("stub2" in m for m in stubs))
        self.assertTrue(any("stub3" in m for m in stubs))
        self.assertFalse(any("active" in m for m in stubs))

    def test_comment_scanning(self):
        code = """# generated by copilot
# TODO: implement this
# normal comment
"""
        issues = detect_issues(code, "test.py")
        comments = [i.message for i in issues if i.issue_type == "placeholder_var" and "comment:" in i.message.lower()]
        self.assertEqual(len(comments), 2)

    def test_fix_unused_imports(self):
        code = """import sys
from collections import defaultdict, Counter

d = defaultdict(int)
"""
        fixed = fix_file(code, "test.py")
        self.assertIn("# vibecheck-removed: import sys", fixed)
        self.assertIn("# vibecheck-removed: from collections import defaultdict, Counter", fixed)
        self.assertIn("from collections import defaultdict", fixed)
        self.assertNotIn("Counter", fixed.splitlines()[-1]) # Counter is removed in the recreated import

    def test_fix_dead_functions(self):
        code = """def dead_func():
    return 1

print("hello")
"""
        fixed = fix_file(code, "test.py")
        self.assertIn("# vibecheck-removed: def dead_func():", fixed)
        self.assertIn("# vibecheck-removed:     return 1", fixed)

    def test_fix_placeholder_variables(self):
        code = """API_KEY = "your_api_key_here"
"""
        # API_KEY is a placeholder, should be replaced by os.getenv, and import os added
        fixed = fix_file(code, "test.py")
        self.assertIn("import os", fixed)
        self.assertIn("API_KEY = os.getenv('API_KEY', 'your_api_key_here')", fixed)

if __name__ == "__main__":
    unittest.main()
