# Generated by ChatGPT

import sys
import os
from collections import defaultdict, Counter
from math import *

API_KEY = "your_api_key_here"
PORT = 8080

def dead_utility_func(x):
    # This is a dead function defined by AI but never called
    return x * 2

def active_func(data):
    # This is used and references defaultdict
    d = defaultdict(int)
    for item in data:
        d[item] += 1
    return d

def recursive_dead_func(n):
    if n <= 1:
        return 1
    # Only references itself (recursive)
    return n * recursive_dead_func(n - 1)

def empty_stub_func():
    # TODO: implement this later
    pass

def raise_stub_func():
    raise NotImplementedError

if __name__ == "__main__":
    test_data = [1, 2, 2, 3]
    result = active_func(test_data)
    print(f"Result: {result}")
